"""fill data

Revision ID: cf4eef6f3178
Revises: 24f3933d37cb
Create Date: 2023-05-22 13:27:57.502164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4eef6f3178'
down_revision = '24f3933d37cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
